Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: UpdateStatusFunction
      Handler: update_lambda.lambda_handler
      Runtime: python3.9
      CodeUri: ./
      Description: My Python Lambda Function
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt SEPTAExecutionRole.Arn
      Architectures:
        - x86_64

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: SEPTAExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource: 'arn:aws:s3:::septa-regional-rails'
