version = 0.1
[default]
[default.deploy]
    stack_name = "DailySchedule" 
    s3_bucket = "septa-regional-rails" 
    region = "us-east-1"        
    confirm_changeset = true      
    capabilities = "CAPABILITY_IAM"